### ISSUE TITLE
비콘 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by JungHunPark** [wizTurn/Android-SDK#75]
안녕하세요 비콘관련해서 앱을 만들고있는 학생입니다.
저희가 이번에 비콘을 관련해서 실내 네비게이션을 만들려고 하는데여
비콘을 이용해서 핸드폰과 거리를 측정하는것은 했는데
그거리를 좌표로 바꿔서 핸드폰상으로 표시하는 방법에 대해서 알려주시면 감사하겠습니다.

**Comment by jayjay-dio** [comment]
현재 측위에 널리 쓰이는 방식은 삼각측량(Triangulation)입니다. 관련 자료는 구글링을 통해서도 쉽게 얻으실 수 있으십니다.
